### ISSUE TITLE
[ Suggestion ] Quite Aggresive Warning

### ISSUE THREAD

**Issue by Blair2004** [notrinos/NotrinosERP#12]
While using the demo, i've come to see this warning.

![image](https://user-images.githubusercontent.com/5265663/135550859-482fec09-5711-4193-8c67-2328524174c7.png)

I believe the words used are quite aggressive: "You have been warned".

**Comment by notrinos** [comment]
Hi @Blair2004 
How should we replace it with?
Thank you for your suggestion.
