### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [notrinos/NotrinosERP#13]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nickshadows) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by notrinos** [comment]
[Added SECURITY.md](https://github.com/notrinos/NotrinosERP/commit/a7c95463e1fdeec7c3b70a2c3457abb0143a194f)

**Comment by JamieSlome** [comment]
@notrinos - you should have just received an e-mail with further information.

Just for reference, the report can also be found here:
https://huntr.dev/bounties/61126c07-22ac-4961-a198-1aa33060b373/

**Comment by notrinos** [comment]
[The problem has been solved now](https://github.com/notrinos/NotrinosERP/commit/0362778f4f678156c22a009094225823df8a4760)
Thanks @JamieSlome
