### ISSUE TITLE
Vietnamese language

### ISSUE THREAD

**Issue by saosangmo** [notrinos/NotrinosERP#14]
hi,
Could you port some strings from quanlyviet into Vietnamese language package. I will translate the rest of file.
Many thanks

**Comment by notrinos** [comment]
Hi @saosangmo 

That would be great
But first I have to add Vietnamese language to the original repository
We don't have Vietnamese language package currently.
This may take some times and I will inform once the new package is added.
And could you please post this discussion [into our forums](https://forums.notrinos.com/) ? I will create a new forum for language translations.
Thank you

**Comment by saosangmo** [comment]
I have already made request on the forum.
