### ISSUE TITLE
Cannot find widget file '812'

### ISSUE THREAD

**Issue by saosangmo** [notrinos/NotrinosERP#15]
# Bug
`Cannot find widget file '812'` on the dashboard

## Environment
- **Version**: 0.7
- **OS**: Mac OS X
- **Web server**: Apache
- **PHP**: 8.1
- **Database**: MySQL 8
- **URL(s)**: [[*Affected URL(s)*]](http://localhost/notrinos/admin/dashboard.php?sel_app=system)
<img width="1327" alt="Screen Shot 2022-09-30 at 20 07 48" src="https://user-images.githubusercontent.com/4606931/193276434-713bcf2f-84e4-4532-afdc-4135332a3a1a.png">

**Comment by sambadabudiarga** [comment]
For anyone who may find this issue.
The simplest way to suppress the error is commenting the code in **admin/dashboard.php**,
```
// $dashboard->addWidget(DA_SETUP, 812, WIDGET_HALF);
```

Or, you can just copy paste the widget file in **dashboard/widget811.php** to **dashboard/widget812.php** 

Just choose one of the above.
